name: htx
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - aom=3.9.1
  - appdirs=1.4.4
  - appnope=0.1.4
  - arrow-cpp=13.0.0
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - audioread=3.0.1
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - blas=1.0
  - blinker=1.9.0
  - boost-cpp=1.85.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cairo=1.18.4
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.11.0
  - datasets=2.19.2
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - dill=0.3.8
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - ffmpeg=7.1.0
  - filelock=3.17.0
  - flask=3.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gdk-pixbuf=2.42.12
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=11.2.1
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=13.0.0
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libass=0.17.3
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=20.1.7
  - libdeflate=1.24
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.24.1
  - libintl-devel=0.24.1
  - libjpeg-turbo=3.1.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopenvino=2024.4.0
  - libopenvino-arm-cpu-plugin=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.3.1
  - libpng=1.6.49
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librosa=0.10.2.post1
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.0.7
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numba=0.60.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.5.0
  - openjpeg=2.5.3
  - openssl=3.5.0
  - orc=2.0.1
  - packaging=25.0
  - pandas=2.2.3
  - pango=1.56.3
  - parso=0.8.4
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.2
  - platformdirs=4.3.8
  - pooch=1.4.0
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - pyarrow=13.0.0
  - pyarrow-hotfix=0.7
  - pybind11-abi=4
  - pycparser=2.21
  - pygments=2.19.2
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.9.23
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.4
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - soxr=0.1.3
  - soxr-python=0.5.0.post1
  - sqlite=3.50.1
  - stack_data=0.6.3
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.52.4
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.8.1
      - evaluate==0.4.4
      - hf-xet==1.1.5
      - huggingface-hub==0.31.2
      - instructorembedding==1.0.2
      - jiwer==4.0.0
      - nltk==3.9.1
      - protobuf==6.31.1
      - rapidfuzz==3.13.0
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - soundfile==0.13.1
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
